YELLOW = (255, 255, 0)
WHITE = (255, 255, 255)
GAME_RESTART_COLOR = YELLOW
GAME_STATS_COLOR = WHITE

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_CAPTION = "Asteroids of Cement"
GAME_LIVES = 3
GAME_RESTARTS_IN = 1024
GAME_BANNER_EDGE_OFFSET = 16
VIRTUAL_SCREEN_EDGE_OFFSET_POSITIVE = 128
VIRTUAL_SCREEN_EDGE_OFFSET_NEGATIVE = -128

MAX_RESPAWN_SPRITE_WIDTH_POSITIVE = 32
MAX_RESPAWN_SPRITE_WIDTH_NEGATIVE = MAX_RESPAWN_SPRITE_WIDTH_POSITIVE * -1

VIRTUAL_SCREEN_RESPAWN_STRIP_LEFT_FROM = VIRTUAL_SCREEN_EDGE_OFFSET_NEGATIVE
VIRTUAL_SCREEN_RESPAWN_STRIP_LEFT_TO = MAX_RESPAWN_SPRITE_WIDTH_NEGATIVE
VIRTUAL_SCREEN_RESPAWN_STRIP_RIGHT_FROM = SCREEN_WIDTH + MAX_RESPAWN_SPRITE_WIDTH_POSITIVE
VIRTUAL_SCREEN_RESPAWN_STRIP_RIGHT_TO = SCREEN_WIDTH + MAX_RESPAWN_SPRITE_WIDTH_POSITIVE \
                                        + VIRTUAL_SCREEN_EDGE_OFFSET_POSITIVE
VIRTUAL_SCREEN_RESPAWN_STRIP_TOP_FROM = VIRTUAL_SCREEN_EDGE_OFFSET_NEGATIVE
VIRTUAL_SCREEN_RESPAWN_STRIP_TOP_TO = MAX_RESPAWN_SPRITE_WIDTH_NEGATIVE
VIRTUAL_SCREEN_RESPAWN_STRIP_BOTTOM_FROM = SCREEN_HEIGHT + MAX_RESPAWN_SPRITE_WIDTH_POSITIVE
VIRTUAL_SCREEN_RESPAWN_STRIP_BOTTOM_TO = SCREEN_HEIGHT + VIRTUAL_SCREEN_EDGE_OFFSET_POSITIVE

BACKGROUND_STARS_COUNT = 256
FPS_LIMIT = 120
